spring:
  application:
    name: rabbitmq-services
  rabbitmq:
    host: localhost
    port: 5672
    addresses: localhost:5672
    username: dev1234
    password: dev1234
    virtual-host: /
    dynamic:  true
server:
  port: 8081

variables:
  exchange: webflux
  routing: webflux_key
  queue: demo_webflux
  durable: false
  exchange2: webflux
  routing2: webflux_key
  queue2: demo_webflux
  queue3: demo_webflux
