version: "3"

services:
  rabbitmq-container:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "dev1234"
      RABBITMQ_DEFAULT_PASS: "dev1234"
      RABBITMQ_DEFAULT_VHOST: "/"

  app-container:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq-container
      - SPRING_RABBITMQ_ADDRESSES=rabbitmq-container:5672
    depends_on:
      - rabbitmq-container
