spring:
  application:
    name: spring-reactor-rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    addresses: localhost:5672
    username: dev1234
    password: dev1234
    virtual-host: /
    dynamic:  true
server:
  port: 8081

project:
  version: trunk.20201123.1

variables:
  exchange: webflux
  routing: webflux_key
  queue: demo_webflux
  durable: false
  autodelete: true
  version: trunk.20201123.1

management:
  health:
    ping:
      enabled: false
    diskspace:
      enabled: false
    rabbit:
      enabled: true
    versionDeploy:
      enabled: true
  endpoint:
    health:
      show-details: always

movement:
  url: https://movements-api.getsandbox.com:443/jsierra93/movimientos_depositos/1.0.0/health
